[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "3sJjr8BspgJc3K1KKxFDPU1QSH5PG3PoHs5xLRzR52fT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vikasbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
